FROM node:18-alpine AS base

FROM base AS builder

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock lerna.json ./

COPY ./packages/shared/package.json ./packages/shared/
COPY ./packages/web/package.json ./packages/web/

# lerna is devDependency => production should be false
RUN yarn --frozen-lockfile --production=false

ENV PATH /app/node_modules/.bin:$PATH

COPY . /app

RUN yarn build:shared
RUN yarn build:web

RUN cd /app/packages/web/.next/standalone/packages/web

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/packages/web/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/packages/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/packages/web/.next/static /app/packages/web/.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

CMD ["node", "/app/packages/web/server.js"]