import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Configs from "./config";
import React, { FC } from "react";
import Wrappers from "../HOC";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className} style={{ padding: 0, margin: 0 }}>
        <Configs>
          <Wrappers>{children}</Wrappers>
        </Configs>
      </body>
    </html>
  );
};

export default RootLayout;
